# -*- coding: utf-8 -*-
"""SPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUjgAaidwX-K-PF6t1Ml5Xr0SnOTD7X8
"""

import pandas as pd

try:
    data = pd.read_csv("/content/student_performance.csv")
    print("Dataset loaded successfully!")
    print("===== STUDENT MANAGEMENT SYSTEM =====")
    print("\nDataset loaded successfully!")

    print("\nNumber of Students:", len(data))

    print("\nColumns:")
    print(data.columns.tolist())

    print("\nFirst 5 Students:")
    print(data.head())

except FileNotFoundError:
    print("Error: Dataset file not found.")

except Exception as e:
    print("An error occurred:", e)

#create a dataframe
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df.head())

data["result"] = data["grade"].apply(
    lambda x: "Pass" if x in ["A", "B", "C"] else "Fail"
)

print("\n===== STUDENT RESULT =====")
print(data[[
    "student_id",
    "total_score",
    "grade",
    "result"
]].head(10))

def display_student(student_id):

    student = data[
        data["student_id"] == student_id
    ]

    if student.empty:
        print("Student not found.")
        return

    student = student.iloc[0]

    print("\n===== STUDENT DETAILS =====")

    print("Student ID:",
          student["student_id"])

    print("Weekly Study Hours:",
          student["weekly_self_study_hours"])

    print("Attendance:",
          student["attendance_percentage"], "%")

    print("Class Participation:",
          student["class_participation"])

    print("Total Score:",
          student["total_score"])

    print("Grade:",
          student["grade"])

    print("Result:",
          student["result"])
display_student(1)

def search_student():

    student_id = int(
        input("Enter Student ID: ")
    )

    student = data[
        data["student_id"] == student_id
    ]

    if student.empty:

        print("\nStudent not found.")

    else:

        print("\n===== STUDENT FOUND =====")

        print(student.to_string(index=False))
search_student()

def add_student():

    global data

    print("\n========== ADD NEW STUDENT ==========")

    # Student ID
    student_id = int(input("Enter Student ID: "))

    # Check if ID already exists
    if student_id in data["student_id"].values:
        print("Student ID already exists.")
        return

    # Input student information
    study_hours = float(
        input("Enter Weekly Self Study Hours: ")
    )

    attendance = float(
        input("Enter Attendance Percentage: ")
    )

    participation = float(
        input("Enter Class Participation: ")
    )

    total_score = float(
        input("Enter Total Score: ")
    )

    # Calculate grade
    if total_score >= 90:
        grade = "A"
    elif total_score >= 80:
        grade = "B"
    elif total_score >= 70:
        grade = "C"
    elif total_score >= 60:
        grade = "D"
    else:
        grade = "F"

    # Calculate result
    if total_score >= 40:
        result = "Pass"
    else:
        result = "Fail"

    # Create new student
    new_student = pd.DataFrame({
        "student_id": [student_id],
        "weekly_self_study_hours": [study_hours],
        "attendance_percentage": [attendance],
        "class_participation": [participation],
        "total_score": [total_score],
        "grade": [grade],
        "result": [result]
    })

    # Add student to DataFrame
    data = pd.concat(
        [data, new_student],
        ignore_index=True
    )

    # Save to CSV
    data.to_csv(
        "student_performance(1).csv",
        index=False
    )

    print("\nStudent added successfully!")

    print("\n----- Student Details -----")
    print("Student ID:", student_id)
    print("Grade:", grade)
    print("Result:", result)
add_student()

def update_student():

    global data

    print("\n========== UPDATE STUDENT ==========")

    student_id = int(input("Enter Student ID: "))

    # Find student
    index = data.index[
        data["student_id"] == student_id
    ]

    if len(index) == 0:
        print("Student not found.")
        return

    # Enter new details
    study_hours = float(
        input("Enter New Weekly Self Study Hours: ")
    )

    attendance = float(
        input("Enter New Attendance Percentage: ")
    )

    participation = float(
        input("Enter New Class Participation: ")
    )

    total_score = float(
        input("Enter New Total Score: ")
    )

    # Calculate grade
    if total_score >= 90:
        grade = "A"
    elif total_score >= 80:
        grade = "B"
    elif total_score >= 70:
        grade = "C"
    elif total_score >= 60:
        grade = "D"
    else:
        grade = "F"

    # Calculate result
    if total_score >= 40:
        result = "Pass"
    else:
        result = "Fail"

    # Update student
    data.loc[index[0], "weekly_self_study_hours"] = study_hours
    data.loc[index[0], "attendance_percentage"] = attendance
    data.loc[index[0], "class_participation"] = participation
    data.loc[index[0], "total_score"] = total_score
    data.loc[index[0], "grade"] = grade
    data.loc[index[0], "result"] = result

    # Save changes
    data.to_csv(
        "student_performance(1).csv",
        index=False
    )

    print("\nStudent updated successfully!")

    print("\n----- Updated Details -----")
    print("Student ID:", student_id)
    print("Study Hours:", study_hours)
    print("Attendance:", attendance, "%")
    print("Participation:", participation)
    print("Total Score:", total_score)
    print("Grade:", grade)
    print("Result:", result)
update_student()

def delete_student():

    global data

    print("\n========== DELETE STUDENT ==========")

    student_id = int(input("Enter Student ID: "))

    # Check if student exists
    if student_id not in data["student_id"].values:
        print("Student not found.")
        return

    # Delete student
    data = data[
        data["student_id"] != student_id
    ]

    # Reset index
    data = data.reset_index(drop=True)

    # Save changes to CSV
    data.to_csv(
        "student_performance(1).csv",
        index=False
    )

    print("\nStudent deleted successfully!")
delete_student()

def display_students():

    print("\n========== DISPLAY STUDENTS ==========")

    print("1. Show First 10 Students")
    print("2. Show Last 10 Students")
    print("3. Show Pass Students")
    print("4. Show Fail Students")
    print("5. Show Students by Grade")

    choice = input("\nEnter your choice: ")

    if choice == "1":

        print("\n----- First 10 Students -----")

        print(
            data.head(10).to_string(index=False)
        )

    elif choice == "2":

        print("\n----- Last 10 Students -----")

        print(
            data.tail(10).to_string(index=False)
        )

    elif choice == "3":

        pass_students = data[
            data["result"] == "Pass"
        ]

        print("\n----- Pass Students -----")

        print(
            pass_students.head(20)
            .to_string(index=False)
        )

        print(
            "\nTotal Pass Students:",
            len(pass_students)
        )

    elif choice == "4":

        fail_students = data[
            data["result"] == "Fail"
        ]

        print("\n----- Fail Students -----")

        print(
            fail_students.head(20)
            .to_string(index=False)
        )

        print(
            "\nTotal Fail Students:",
            len(fail_students)
        )

    elif choice == "5":

        grade = input(
            "Enter Grade (A/B/C/D/F): "
        ).upper()

        grade_students = data[
            data["grade"] == grade
        ]

        if grade_students.empty:

            print("\nNo students found for this grade.")

        else:

            print(
                f"\n----- Grade {grade} Students -----"
            )

            print(
                grade_students.head(20)
                .to_string(index=False)
            )

            print(
                "\nTotal Students:",
                len(grade_students)
            )

    else:

        print("\nInvalid choice.")
display_students()

def performance_analysis():

    print("\n========== PERFORMANCE ANALYSIS ==========")

    # Total number of students
    total_students = len(data)

    # Score analysis using NumPy
    scores = data["total_score"].to_numpy()

    average_score = np.mean(scores)
    highest_score = np.max(scores)
    lowest_score = np.min(scores)
    median_score = np.median(scores)
    standard_deviation = np.std(scores)

    # Attendance analysis
    average_attendance = np.mean(
        data["attendance_percentage"]
    )

    highest_attendance = np.max(
        data["attendance_percentage"]
    )

    lowest_attendance = np.min(
        data["attendance_percentage"]
    )

    # Study hours analysis
    average_study_hours = np.mean(
        data["weekly_self_study_hours"]
    )

    # Participation analysis
    average_participation = np.mean(
        data["class_participation"]
    )

    # Display results
    print("\n----- General Information -----")

    print(
        "Total Students:",
        total_students
    )

    print("\n----- Score Analysis -----")

    print(
        "Average Score:",
        round(average_score, 2)
    )

    print(
        "Highest Score:",
        highest_score
    )

    print(
        "Lowest Score:",
        lowest_score
    )

    print(
        "Median Score:",
        round(median_score, 2)
    )

    print(
        "Standard Deviation:",
        round(standard_deviation, 2)
    )

    print("\n----- Attendance Analysis -----")

    print(
        "Average Attendance:",
        round(average_attendance, 2),
        "%"
    )

    print(
        "Highest Attendance:",
        highest_attendance,
        "%"
    )

    print(
        "Lowest Attendance:",
        lowest_attendance,
        "%"
    )

    print("\n----- Study & Participation -----")

    print(
        "Average Weekly Study Hours:",
        round(average_study_hours, 2)
    )

    print(
        "Average Class Participation:",
        round(average_participation, 2)
    )
performance_analysis()

def grade_analysis():

    print("\n========== GRADE & RESULT ANALYSIS ==========")

    # Grade-wise count
    grade_count = data["grade"].value_counts()

    print("\n----- Grade Distribution -----")

    for grade, count in grade_count.items():
        print(
            "Grade", grade,
            ":", count,
            "students"
        )

    # Pass and Fail count
    pass_count = (data["result"] == "Pass").sum()
    fail_count = (data["result"] == "Fail").sum()

    total_students = len(data)

    # Percentages
    pass_percentage = (
        pass_count / total_students
    ) * 100

    fail_percentage = (
        fail_count / total_students
    ) * 100

    print("\n----- Pass / Fail Analysis -----")

    print(
        "Pass Students:",
        pass_count
    )

    print(
        "Fail Students:",
        fail_count
    )

    print(
        "Pass Percentage:",
        round(pass_percentage, 2),
        "%"
    )

    print(
        "Fail Percentage:",
        round(fail_percentage, 2),
        "%"
    )
grade_analysis()

from scipy import stats
import numpy as np


def statistical_analysis():

    print("\n========== STATISTICAL ANALYSIS ==========")

    # Get total scores
    scores = data["total_score"].dropna().to_numpy()

    # Central tendency
    mean = np.mean(scores)
    median = np.median(scores)
    mode = stats.mode(scores, keepdims=True).mode[0]

    # Dispersion
    standard_deviation = np.std(scores)
    variance = np.var(scores)

    # Shape of distribution
    skewness = stats.skew(scores)
    kurtosis = stats.kurtosis(scores)

    # 95% Confidence Interval
    confidence_interval = stats.t.interval(
        0.95,
        len(scores) - 1,
        loc=mean,
        scale=stats.sem(scores)
    )

    print("\n----- Central Tendency -----")

    print(
        "Mean:",
        round(mean, 2)
    )

    print(
        "Median:",
        round(median, 2)
    )

    print(
        "Mode:",
        mode
    )

    print("\n----- Dispersion -----")

    print(
        "Standard Deviation:",
        round(standard_deviation, 2)
    )

    print(
        "Variance:",
        round(variance, 2)
    )

    print("\n----- Distribution Shape -----")

    print(
        "Skewness:",
        round(skewness, 4)
    )

    print(
        "Kurtosis:",
        round(kurtosis, 4)
    )

    print("\n----- 95% Confidence Interval -----")

    print(
        "Lower Limit:",
        round(confidence_interval[0], 2)
    )

    print(
        "Upper Limit:",
        round(confidence_interval[1], 2)
    )
statistical_analysis()

import matplotlib.pyplot as plt
import seaborn as sns
def study_score_analysis():

    correlation = data[
        [
            "weekly_self_study_hours",
            "total_score"
        ]
    ].corr()

    print("===== CORRELATION =====")
    print(correlation)

    plt.figure(figsize=(8, 5))

    sns.scatterplot(
        data=data,
        x="weekly_self_study_hours",
        y="total_score"
    )

    plt.title(
        "Study Hours vs Total Score"
    )

    plt.xlabel("Weekly Study Hours")
    plt.ylabel("Total Score")

    plt.show()
study_score_analysis()

import matplotlib.pyplot as plt
import seaborn as sns


def visualization():

    print("\n========== DATA VISUALIZATION ==========")

    # -------------------------------
    # 5. Attendance vs Score
    # -------------------------------

    plt.figure(figsize=(8, 5))

    sns.scatterplot(
        data=data,
        x="attendance_percentage",
        y="total_score",
        hue="grade"
    )

    plt.title(
        "Attendance vs Total Score"
    )

    plt.xlabel("Attendance Percentage")
    plt.ylabel("Total Score")

    plt.show()
visualization()

import numpy as np
from scipy import stats


def sampling_analysis():

    print("\n========== SAMPLING ANALYSIS ==========")

    # Get total scores
    scores = data["total_score"].dropna().to_numpy()

    # Population mean
    population_mean = np.mean(scores)

    print("\nPopulation Mean:",
          round(population_mean, 2))

    # Select random sample
    sample_size = 100

    sample = np.random.choice(
        scores,
        size=sample_size,
        replace=False
    )

    # Calculate sample mean
    sample_mean = np.mean(sample)

    print("Sample Size:",
          sample_size)

    print("Sample Mean:",
          round(sample_mean, 2))

    # 95% Confidence Interval
    confidence_interval = stats.t.interval(
        0.95,
        len(sample) - 1,
        loc=sample_mean,
        scale=stats.sem(sample)
    )

    print("\n----- 95% Confidence Interval -----")

    print(
        "Lower Limit:",
        round(confidence_interval[0], 2)
    )

    print(
        "Upper Limit:",
        round(confidence_interval[1], 2)
    )

    # Central Limit Theorem
    sample_means = []

    for i in range(1000):

        random_sample = np.random.choice(
            scores,
            size=100,
            replace=True
        )

        sample_means.append(
            np.mean(random_sample)
        )

    mean_of_sample_means = np.mean(
        sample_means
    )

    print("\n----- Central Limit Theorem -----")

    print(
        "Mean of Sample Means:",
        round(mean_of_sample_means, 2)
    )

    print(
        "Population Mean:",
        round(population_mean, 2)
    )
sampling_analysis()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


def ml_prediction():

    print("\n========== ML PASS/FAIL PREDICTION ==========")

    # Create Pass/Fail target
    # A, B, C = Pass
    # D, F = Fail
    data["result"] = data["grade"].apply(
        lambda x: 1 if x in ["A", "B", "C"] else 0
    )

    # Features
    X = data[
        [
            "weekly_self_study_hours",
            "attendance_percentage",
            "class_participation"
        ]
    ]

    # Target
    y = data["result"]

    # Split dataset
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
        stratify=y
    )

    # Create Logistic Regression model
    model = LogisticRegression(
        max_iter=1000
    )

    # Train model
    model.fit(X_train, y_train)

    # Predict test data
    y_pred = model.predict(X_test)

    # Accuracy
    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    print("\n----- Model Result -----")

    print(
        "Accuracy:",
        round(accuracy * 100, 2),
        "%"
    )

    print("\n----- Classification Report -----")

    print(
        classification_report(
            y_test,
            y_pred,
            target_names=["Fail", "Pass"]
        )
    )

    # Predict new student
    print("\n----- New Student Prediction -----")

    study_hours = float(
        input("Enter Weekly Self Study Hours: ")
    )

    attendance = float(
        input("Enter Attendance Percentage: ")
    )

    participation = float(
        input("Enter Class Participation: ")
    )

    new_student = [[
        study_hours,
        attendance,
        participation
    ]]

    prediction = model.predict(
        new_student
    )

    probability = model.predict_proba(
        new_student
    )

    if prediction[0] == 1:

        print("\nPrediction: PASS")

        print(
            "Pass Probability:",
            round(probability[0][1] * 100, 2),
            "%"
        )

    else:

        print("\nPrediction: FAIL")

        print(
            "Fail Probability:",
            round(probability[0][0] * 100, 2),
            "%"
        )
ml_prediction()

!pip install reportlab

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

# Load dataset
data = pd.read_csv("/content/student_performance.csv")

# Create Pass/Fail result
data["result"] = data["grade"].apply(
    lambda x: "Pass" if x in ["A", "B", "C"] else "Fail"
)

# Function to generate PDF
def generate_student_report(student_id):

    # Find student
    student = data[
        data["student_id"] == student_id
    ]

    if student.empty:
        print("Student not found.")
        return

    student = student.iloc[0]

    # PDF filename
    filename = f"Student_Report_{student_id}.pdf"

    # Create PDF
    document = SimpleDocTemplate(
        filename,
        pagesize=A4
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    normal_style = styles["Normal"]

    content = []

    # Title
    content.append(
        Paragraph(
            "STUDENT PERFORMANCE REPORT",
            title_style
        )
    )

    content.append(Spacer(1, 20))

    # Student information
    student_data = [
        ["Student ID", str(student["student_id"])],
        [
            "Weekly Self Study Hours",
            str(student["weekly_self_study_hours"])
        ],
        [
            "Attendance Percentage",
            str(student["attendance_percentage"]) + "%"
        ],
        [
            "Class Participation",
            str(student["class_participation"])
        ],
        [
            "Total Score",
            str(student["total_score"])
        ],
        [
            "Grade",
            str(student["grade"])
        ],
        [
            "Result",
            str(student["result"])
        ]
    ]

    # Create table
    table = Table(
        student_data,
        colWidths=[220, 180]
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    content.append(table)

    content.append(Spacer(1, 30))

    content.append(
        Paragraph(
            "Generated by Student Management System",
            normal_style
        )
    )

    # Generate PDF
    document.build(content)

    print(
        f"PDF report generated successfully: {filename}"
    )


# Enter Student ID
student_id = int(
    input("Enter Student ID: ")
)

generate_student_report(student_id)
